# Generated by Django 4.0.3 on 2022-03-11 09:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('body', models.CharField(default='Body text here', max_length=100000)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Genric Title', max_length=100)),
                ('href', models.CharField(default='#', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=6)),
                ('base_body_weight_kg', models.FloatField(default=0)),
                ('base_body_fat_p', models.FloatField(default=0)),
                ('base_visceral_fat', models.FloatField(default=0)),
                ('base_bone_mass_kg', models.FloatField(default=0)),
                ('base_bmr', models.FloatField(default=0)),
                ('base_metabolic_age', models.FloatField(default=0)),
                ('base_muscle_mass_kg', models.FloatField(default=0)),
                ('base_physique_rating', models.FloatField(default=0)),
                ('base_water', models.FloatField(default=0)),
                ('base_body_fat_kg', models.FloatField(default=0)),
                ('base_muscle_mass_p', models.FloatField(default=0)),
                ('current_body_weight_kg', models.FloatField(default=0)),
                ('current_body_fat_p', models.FloatField(default=0)),
                ('current_visceral_fat', models.FloatField(default=0)),
                ('current_bone_mass_kg', models.FloatField(default=0)),
                ('current_bmr', models.FloatField(default=0)),
                ('current_metabolic_age', models.FloatField(default=0)),
                ('current_muscle_mass_kg', models.FloatField(default=0)),
                ('current_physique_rating', models.FloatField(default=0)),
                ('current_water', models.FloatField(default=0)),
                ('current_body_fat_kg', models.FloatField(default=0)),
                ('current_muscle_mass_p', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
